### Create todo
POST {{local_url}}api/todos
Content-Type: application/json
Accept: application/json
Authorization:{{token}}

{
  "title": "First task title",
  "description": "This is my first task",
  "status": 1
}

### Update todo
PUT {{local_url}}api/todos/65abc3576b84fc8f00a7d572
Content-Type: application/json
Accept: application/json
Authorization:{{token}}

{
  "title": "update task title",
  "description": "Update task",
  "status": 2
}
