### Create todo
POST {{local_url}}api/todos
Content-Type: application/json
Accept: application/json
Authorization:{{token}}

{
  "title": "2nd task title",
  "description": "This is my 2nd task",
  "status": 1
}

### Update todo
PUT {{local_url}}api/todos/65abe352badca4e0a106260a
Content-Type: application/json
Accept: application/json
Authorization:{{token}}

{
  "title": "update task title again",
  "description": "Update task",
  "status": 2
}

### Restore todo
GET {{local_url}}api/todos/restore/65abe352badca4e0a106260a
Content-Type: application/json
Accept: application/json
Authorization:{{token}}


### Delete todo
DELETE {{local_url}}api/todos/65abe352badca4e0a106260a
Content-Type: application/json
Accept: application/json
Authorization:{{token}}


### GET todos
GET {{local_url}}api/todos
Content-Type: application/json
Accept: application/json
Authorization:{{token}}

### Find todos
GET {{local_url}}api/todos/65ac1caf0e8877e165eafe5d
Content-Type: application/json
Accept: application/json
Authorization:{{token}}

