### Find user
GET {{local_url}}api/users/65ab9dc105100710fba6733b
Content-Type: application/json
Accept: application/json
Authorization:{{token}}

{
    "name": "hamza",
    "password": "12345678",
    "email": "test1@example.com"
}

### Get users list
GET {{local_url}}api/users
Content-Type: application/json
Accept: application/json
Authorization:{{token}}

{
    "email": "test1@example.com",
    "password": "12345678"
}
